// <auto-generated/>
#nullable enable
namespace Zaya.ScreenTranslator.Impl.Shared.Properties;

/// <summary>
/// A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
internal sealed class Resources
{
    private readonly System.Resources.ResourceManager _rm = new(
        "Zaya.ScreenTranslator.Impl.Shared.Properties.Resources",
        typeof(Resources).Assembly);

    internal static Resources Instance { get; } = new();

    internal string GetString(string name, System.Globalization.CultureInfo? culture = null)
        => _rm.GetString(name, culture) ?? $"#{name}#";
}
