//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaya.ScreenTranslator.Impl.Layout.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zaya.ScreenTranslator.Impl.Layout.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Overlay_Background {
            get {
                return ResourceManager.GetString("Overlay_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background behind overlay text.
        /// </summary>
        internal static string Overlay_Background_Desc {
            get {
                return ResourceManager.GetString("Overlay_Background_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Overlay_Background_None {
            get {
                return ResourceManager.GetString("Overlay_Background_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaque.
        /// </summary>
        internal static string Overlay_Background_Opaque {
            get {
                return ResourceManager.GetString("Overlay_Background_Opaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft.
        /// </summary>
        internal static string Overlay_Background_Soft {
            get {
                return ResourceManager.GetString("Overlay_Background_Soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background opacity (%).
        /// </summary>
        internal static string Overlay_BackgroundOpacity {
            get {
                return ResourceManager.GetString("Overlay_BackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity of soft/opaque background.
        /// </summary>
        internal static string Overlay_BackgroundOpacity_Desc {
            get {
                return ResourceManager.GetString("Overlay_BackgroundOpacity_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws text over the target window by coordinates.
        /// </summary>
        internal static string Overlay_EngineDesc {
            get {
                return ResourceManager.GetString("Overlay_EngineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen overlay.
        /// </summary>
        internal static string Overlay_EngineName {
            get {
                return ResourceManager.GetString("Overlay_EngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit mode.
        /// </summary>
        internal static string Overlay_FitMode {
            get {
                return ResourceManager.GetString("Overlay_FitMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip.
        /// </summary>
        internal static string Overlay_FitMode_Clip {
            get {
                return ResourceManager.GetString("Overlay_FitMode_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to fit long text into bounds width.
        /// </summary>
        internal static string Overlay_FitMode_Desc {
            get {
                return ResourceManager.GetString("Overlay_FitMode_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink.
        /// </summary>
        internal static string Overlay_FitMode_Shrink {
            get {
                return ResourceManager.GetString("Overlay_FitMode_Shrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap.
        /// </summary>
        internal static string Overlay_FitMode_Wrap {
            get {
                return ResourceManager.GetString("Overlay_FitMode_Wrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font scale (%).
        /// </summary>
        internal static string Overlay_FontScale {
            get {
                return ResourceManager.GetString("Overlay_FontScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size as percent of bounds height.
        /// </summary>
        internal static string Overlay_FontScale_Desc {
            get {
                return ResourceManager.GetString("Overlay_FontScale_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y offset (px).
        /// </summary>
        internal static string Overlay_OffsetY {
            get {
                return ResourceManager.GetString("Overlay_OffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra vertical gap from the bounds edge.
        /// </summary>
        internal static string Overlay_OffsetY_Desc {
            get {
                return ResourceManager.GetString("Overlay_OffsetY_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        internal static string Overlay_Outline {
            get {
                return ResourceManager.GetString("Overlay_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw outline/shadow for readability.
        /// </summary>
        internal static string Overlay_Outline_Desc {
            get {
                return ResourceManager.GetString("Overlay_Outline_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string Overlay_Padding {
            get {
                return ResourceManager.GetString("Overlay_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner padding around overlay text.
        /// </summary>
        internal static string Overlay_Padding_Desc {
            get {
                return ResourceManager.GetString("Overlay_Padding_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement.
        /// </summary>
        internal static string Overlay_Placement {
            get {
                return ResourceManager.GetString("Overlay_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above.
        /// </summary>
        internal static string Overlay_Placement_Above {
            get {
                return ResourceManager.GetString("Overlay_Placement_Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below.
        /// </summary>
        internal static string Overlay_Placement_Below {
            get {
                return ResourceManager.GetString("Overlay_Placement_Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to draw text relative to each bounds box.
        /// </summary>
        internal static string Overlay_Placement_Desc {
            get {
                return ResourceManager.GetString("Overlay_Placement_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        internal static string Overlay_Placement_Over {
            get {
                return ResourceManager.GetString("Overlay_Placement_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        internal static string Overlay_TextColor {
            get {
                return ResourceManager.GetString("Overlay_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string Overlay_TextColor_Auto {
            get {
                return ResourceManager.GetString("Overlay_TextColor_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Overlay_TextColor_Dark {
            get {
                return ResourceManager.GetString("Overlay_TextColor_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground color for overlay text.
        /// </summary>
        internal static string Overlay_TextColor_Desc {
            get {
                return ResourceManager.GetString("Overlay_TextColor_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Overlay_TextColor_Light {
            get {
                return ResourceManager.GetString("Overlay_TextColor_Light", resourceCulture);
            }
        }
    }
}
